<%@ page contentType="text/html;charset=UTF-8" %>

<form class="layui-form" action="">
    <%--网银报告--%>
    <fieldset class="layui-elem-field">
        <legend>1.1用户基本信息</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr>
                <td>姓名：{{user_basic_info.name}}</td>
                <td>邮箱：{{user_basic_info.email}}</td>
            </tr>
              <tr>
                <td>活跃卡数：{{user_basic_info.active_card_num}}</td>
                <td>银行数：{{user_basic_info.bank_num}}</td>
            </tr>
            <tr>
                <td>最初账单日：{{user_basic_info.bill_start_date}}</td>
                <td>最早一期账单距今月份数：{{user_basic_info.bill_start_date_month}}</td>
            </tr>
            <tr>
                <td>客户族群标志：{{user_basic_info.pvcu_customer_group_tag}}</td>
                <td>客户套现标志：{{user_basic_info.pvcu_cashouts_tag}}</td>
            </tr>
            <tr>
                <td colspan="2">账单最新认证时间：{{user_basic_info.latest_certification_time}}</td>
            </tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>1.2授信情况</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr><td>总信用额</td><td>{{account_summary.creditcard_limit}}</td></tr>
			<tr><td>消费信用额</td><td>{{account_summary.consume_credit_limit}}</td></tr>
			<tr><td>提现信用额</td><td>{{account_summary.creditcard_cash_limit}}</td></tr>
			<tr><td>可用提现信用额</td><td>{{account_summary.creditcard_cash_balance}}</td></tr>
			<tr><td>可用消费信用额</td><td>{{account_summary.creditcard_balance}}</td></tr>
			<tr><td>总可用信用额</td><td>{{account_summary.total_can_use_consume_limit_1}}</td></tr>
			<tr><td>单一银行最高授信额度</td><td>{{account_summary.single_bank_max_limit}}</td></tr>
			<tr><td>单一银行最低授信额度</td><td>{{account_summary.single_bank_min_limit}}</td></tr>
            </tbody>
        </table>
    </fieldset>
   	<fieldset class="layui-elem-field">
        <legend>1.3交易行为</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr><td>当期新发生消费总金额</td><td>{{credit_card_summary.total_consume_amount_1}}</td></tr>
			<tr><td>当期总透支余额</td><td>{{credit_card_summary.total_new_balance_1}}</td></tr>
			<tr><td>上期应还总额</td><td>{{credit_card_summary.total_last_balance_1}}</td></tr>
			<tr><td>当期最低还款总额</td><td>{{credit_card_summary.total_min_payment_1}}</td></tr>
			<tr><td>上期未还总额</td><td>{{credit_card_summary.last_unrepay_amount}}</td></tr>
			<tr><td>当期新发生消费总笔数</td><td>{{credit_card_summary.total_consume_num_1}}</td></tr>
			<tr><td>当期新发生消费平均金额</td><td>{{credit_card_summary.cur_consume_avg_amount}}</td></tr>
			<tr><td>当期新发生提现总金额</td><td>{{credit_card_summary.cur_cash_amount}}</td></tr>
			<tr><td>当期新发生提现总笔数</td><td>{{credit_card_summary.cur_cash_num}}</td></tr>
			<tr><td>当期新发生提现平均金额</td><td>{{credit_card_summary.cur_cash_avg_amount}}</td></tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>1.4还款</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr><td>还款金额</td><td>{{repayment_summary.repay_amount_1}}</td></tr>
			<tr><td>还款笔数</td><td>{{repayment_summary.repay_num_1}}</td></tr>
			<tr><td>还款率</td><td>{{repayment_summary.repay_ratio_1}}</td></tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>1.5逾期信息</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr><td>逾期账单数量</td><td>{{overdue_information.delay_bill_num_1}}</td></tr>
			<tr><td>未还金额</td><td>{{overdue_information.delay_amount_1}}</td></tr>
			<tr><td>未还金额占比</td><td>{{overdue_information.delay_amount_per_1}}</td></tr>
			<tr><td>逾期标志</td><td>{{overdue_information.delay_tag_1}}</td></tr>
			<tr><td>逾期状态</td><td>{{overdue_information.delay_status_1}}</td></tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>1.6利费信息</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
			<tr><td>总利息</td><td>{{interest_information.delay_interest_1}}</td></tr>
			<tr><td>滞纳金</td><td>{{interest_information.overdue_amount_1}}</td></tr>
			<tr><td>超额金</td><td>{{interest_information.overdue_pay_1}}</td></tr>
			<tr><td>其他费用</td><td>{{interest_information.other_fee_1}}</td></tr>
			<tr><td>收入（利息+滞纳金+超额金+其他费用）</td><td>{{interest_information.income_amt_1}}</td></tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.1销售金额</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>销售金额大于0的月份占比</td>
				<td>{{sales_amount.ratio_sell_month_3}}</td>
				<td>{{sales_amount.ratio_sell_month_6}}</td>
				<td>{{sales_amount.ratio_sell_month_12}}</td>
			</tr>
			<tr>
				<td>月均消费金额</td>
				<td>{{sales_amount.avg_consume_amount_3}}</td>
				<td>{{sales_amount.avg_consume_amount_6}}</td>
				<td>{{sales_amount.avg_consume_amount_12}}</td>
			</tr>
			<tr>
				<td>最高消费金额</td>
				<td>{{sales_amount.creditcard_max_balance_3}}</td>
				<td>{{sales_amount.creditcard_max_balance_6}}</td>
				<td>{{sales_amount.creditcard_max_balance_12}}</td>
			</tr>
			<tr>
				<td>最低消费金额</td>
				<td>{{sales_amount.creditcard_min_balance_3}}</td>
				<td>{{sales_amount.creditcard_min_balance_6}}</td>
				<td>{{sales_amount.creditcard_min_balance_12}}</td>
			</tr>
			<tr>
				<td>提现次数</td>
				<td>{{sales_amount.withdraw_num_cc_3}}</td>
				<td>{{sales_amount.withdraw_num_cc_6}}</td>
				<td>{{sales_amount.withdraw_num_cc_12}}</td>
			</tr>
			<tr>
				<td>提现金额</td>
				<td>{{sales_amount.withdraw_amount_3}}</td>
				<td>{{sales_amount.withdraw_amount_6}}</td>
				<td>{{sales_amount.withdraw_amount_12}}</td>
			</tr>
			<tr>
				<td>有提现月数占比</td>
				<td>{{sales_amount.has_withdrawal_percentage_3m}}</td>
				<td>{{sales_amount.has_withdrawal_percentage_6m}}</td>
				<td>{{sales_amount.has_withdrawal_percentage_12m}}</td>
			</tr>
			<tr>
				<td>月均提现金额</td>
				<td>{{sales_amount.avg_cash_amount_3}}</td>
				<td>{{sales_amount.avg_cash_amount_6}}</td>
				<td>{{sales_amount.avg_cash_amount_12}}</td>
			</tr>
			<tr>
				<td>最近一次提现距今的月数</td>
				<td>{{sales_amount.last_withdrawal_month_num_3}}</td>
				<td>{{sales_amount.last_withdrawal_month_num_6}}</td>
				<td>{{sales_amount.last_withdrawal_month_num_12}}</td>
			</tr>
			<tr>
				<td>首次销售金额</td>
				<td>{{sales_amount.earlyest_sell_amount_3}}</td>
				<td>{{sales_amount.earlyest_sell_amount_6}}</td>
				<td>{{sales_amount.earlyest_sell_amount_12}}</td>
			</tr>
			<tr>
				<td>首次消费金额</td>
				<td>{{sales_amount.earlyest_consume_amount_3}}</td>
				<td>{{sales_amount.earlyest_consume_amount_6}}</td>
				<td>{{sales_amount.earlyest_consume_amount_12}}</td>
			</tr>
			<tr>
				<td>单期最大销售笔数</td>
				<td>{{sales_amount.max_sell_num_3}}</td>
				<td>{{sales_amount.max_sell_num_6}}</td>
				<td>{{sales_amount.max_sell_num_12}}</td>
			</tr>
			<tr>
				<td>有销售的月数</td>
				<td>{{sales_amount.has_sell_month_num_3}}</td>
				<td>{{sales_amount.has_sell_month_num_6}}</td>
				<td>{{sales_amount.has_sell_month_num_12}}</td>
			</tr>
			<tr>
				<td>月均消费笔数</td>
				<td>{{sales_amount.avg_consume_num_3}}</td>
				<td>{{sales_amount.avg_consume_num_6}}</td>
				<td>{{sales_amount.avg_consume_num_12}}</td>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.2余额</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>近1月零售余额/近＊月均零售余额</td>
				<td>{{balance.retail_balance_1_per_3}}</td>
				<td>{{balance.retail_balance_1_per_6}}</td>
				<td>{{balance.retail_balance_1_per_12}}</td>
			</tr>
			<tr>
				<td>近＊月均销售占近＊月均余额比率</td>
				<td>{{balance.avg_amount_per_avg_balance_3}}</td>
				<td>{{balance.avg_amount_per_avg_balance_6}}</td>
				<td>{{balance.avg_amount_per_avg_balance_12}}</td>
			</tr>
			<tr>
				<td>近＊月最高余额距今的月数</td>
				<td>{{balance.max_balance_month_num_3}}</td>
				<td>{{balance.max_balance_month_num_6}}</td>
				<td>{{balance.max_balance_month_num_12}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.3还款</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>近＊月平均还款金额</td>
				<td>{{repayment.avg_pay_amount_3}}</td>
				<td>{{repayment.avg_pay_amount_6}}</td>
				<td>{{repayment.avg_pay_amount_12}}</td>
			</tr>
			<tr>
				<td>近＊月平均还款率</td>
				<td>{{repayment.repay_ratio_avg_3}}</td>
				<td>{{repayment.repay_ratio_avg_6}}</td>
				<td>{{repayment.repay_ratio_avg_12}}</td>
			</tr>
			<tr>
				<td>近＊月最近一次产生还款金额距今的月数</td>
				<td>{{repayment.last_repay_now_num_3}}</td>
				<td>{{repayment.last_repay_now_num_6}}</td>
				<td>{{repayment.last_repay_now_num_12}}</td>
			</tr>
			<tr>
				<td>近＊月有最低还款且不足全额的月数</td>
				<td>{{repayment.minpay_mons_3}}</td>
				<td>{{repayment.minpay_mons_6}}</td>
				<td>{{repayment.minpay_mons_12}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.4额度</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>近＊月平均余额占额度比例</td>
				<td>{{quota.average_balance_per_quota_nearly_3m}}</td>
				<td>{{quota.average_balance_per_quota_nearly_6m}}</td>
				<td>{{quota.average_balance_per_quota_nearly_12m}}</td>
			</tr>
			<tr>
				<td>近＊月销售金额占额度比</td>
				<td>{{quota.propertion_of_sales_amount_quota_3}}</td>
				<td>{{quota.propertion_of_sales_amount_quota_6}}</td>
				<td>{{quota.propertion_of_sales_amount_quota_12}}</td>
			</tr>
			<tr>
				<td>近＊月中最大销售金额占额度比</td>
				<td>{{quota.propertion_of_max_sales_amount_in_quota_3}}</td>
				<td>{{quota.propertion_of_max_sales_amount_in_quota_6}}</td>
				<td>{{quota.propertion_of_max_sales_amount_in_quota_12}}</td>
			</tr>
			<tr>
				<td>近＊月中最小销售金额占额度比</td>
				<td>{{quota.propertion_of_min_sales_amount_in_quota_3}}</td>
				<td>{{quota.propertion_of_min_sales_amount_in_quota_6}}</td>
				<td>{{quota.propertion_of_min_sales_amount_in_quota_12}}</td>
			</tr>
			<tr>
				<td>近＊月最大额度使用率</td>
				<td>{{quota.useage_of_max_quota_3}}</td>
				<td>{{quota.useage_of_max_quota_6}}</td>
				<td>{{quota.useage_of_max_quota_12}}</td>
			</tr>
			<tr>
				<td>近＊月最近一次额度使用率>0的值</td>
				<td>{{quota.last_useage_more_than_0_nearly_3}}</td>
				<td>{{quota.last_useage_more_than_0_nearly_6}}</td>
				<td>{{quota.last_useage_more_than_0_nearly_12}}</td>
			</tr>
			<tr>
				<td>近＊月平均（消费+提现）金额/信用额度</td>
				<td>{{quota.avg_propertion_of_consume_withdrawal_in_quota_3}}</td>
				<td>{{quota.avg_propertion_of_consume_withdrawal_in_quota_6}}</td>
				<td>{{quota.avg_propertion_of_consume_withdrawal_in_quota_12}}</td>
			</tr>
			<tr>
				<td>近＊月中销售金额占额度比大于0.5的月数</td>
				<td>{{quota.propertion_of_sales_amnt_in_quota_more_0_5_num_3}}</td>
				<td>{{quota.propertion_of_sales_amnt_in_quota_more_0_5_num_6}}</td>
				<td>{{quota.propertion_of_sales_amnt_in_quota_more_0_5_num_12}}</td>
			</tr>
			<tr>
				<td>近＊月中销售金额占额度比大于0.9的月数</td>
				<td>{{quota.propertion_of_sales_amnt_in_quota_more_0_9_num_3}}</td>
				<td>{{quota.propertion_of_sales_amnt_in_quota_more_0_9_num_6}}</td>
				<td>{{quota.propertion_of_sales_amnt_in_quota_more_0_9_num_12}}</td>
			</tr>
			<tr>
				<td>最近一期额度使用率与近＊月最大比</td>
				<td>{{quota.max_propertion_of_last_useage_3}}</td>
				<td>{{quota.max_propertion_of_last_useage_6}}</td>
				<td>{{quota.max_propertion_of_last_useage_12}}</td>
			</tr>
			<tr>
				<td>近＊月平均额度</td>
				<td>{{quota.avg_quota_3}}</td>
				<td>{{quota.avg_quota_6}}</td>
				<td>{{quota.avg_quota_12}}</td>
			</tr>
			<tr>
				<td>近＊月最高额度</td>
				<td>{{quota.max_quota_3}}</td>
				<td>{{quota.max_quota_6}}</td>
				<td>{{quota.max_quota_12}}</td>
			</tr>
			<tr>
				<td>近＊月最低额度</td>
				<td>{{quota.min_quota_3}}</td>
				<td>{{quota.min_quota_6}}</td>
				<td>{{quota.min_quota_12}}</td>
			</tr>
			<tr>
				<td>近＊月最小额度使用率</td>
				<td>{{quota.useage_of_min_quota_3}}</td>
				<td>{{quota.useage_of_min_quota_6}}</td>
				<td>{{quota.useage_of_min_quota_12}}</td>
			</tr>
			<tr>
				<td>近＊月平均额度使用率</td>
				<td>{{quota.average_useage_rate_of_quota_nearly_3m}}</td>
				<td>{{quota.average_useage_rate_of_quota_nearly_6m}}</td>
				<td>{{quota.average_useage_rate_of_quota_nearly_12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.5利息</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>有利息的月份数</td>
				<td>{{interest.interest_mons_3}}</td>
				<td>{{interest.interest_mons_6}}</td>
				<td>{{interest.interest_mons_12}}</td>
			</tr>
			<tr>
				<td>有利息月数占比</td>
				<td>{{interest.interest_mon_ratio_3}}</td>
				<td>{{interest.interest_mon_ratio_6}}</td>
				<td>{{interest.interest_mon_ratio_12}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.6收入</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>平均收入</td>
				<td>{{income.credit_incom_avg_3}}</td>
				<td>{{income.credit_incom_avg_6}}</td>
				<td>{{income.credit_incom_avg_12}}</td>
			</tr>
			<tr>
				<td>最低收入距今月份数</td>
				<td>{{income.min_income_now_mons_3}}</td>
				<td>{{income.min_income_now_mons_6}}</td>
				<td>{{income.min_income_now_mons_12}}</td>
			</tr>
			<tr>
				<td>近3个月平均收入与近6个月平均比</td>
				<td colspan="3">{{income.income_avg_3_div_6}}</td>
			</tr>
			<tr>
				<td>近6个月平均收入与近12个月平均比</td>
				<td colspan="3">{{income.income_avg_6_div_12}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.7超额</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>超额的月份数</td>
				<td>{{overrun.beyond_quota_month_num_3m}}</td>
				<td>{{overrun.beyond_quota_month_num_6m}}</td>
				<td>{{overrun.beyond_quota_month_num_12m}}</td>
			</tr>
			<tr>
				<td>最高超额费</td>
				<td>{{overrun.beyond_quota_max_amount_3m}}</td>
				<td>{{overrun.beyond_quota_max_amount_6m}}</td>
				<td>{{overrun.beyond_quota_max_amount_12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.8逾期</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>非延滞期数</td>
				<td>{{overdue_creditcard.non_delayed_periods_num_3}}</td>
				<td>{{overdue_creditcard.non_delayed_periods_num_6}}</td>
				<td>{{overdue_creditcard.non_delayed_periods_num_12}}</td>
			</tr>
			<tr>
				<td>延滞期数</td>
				<td>{{overdue_creditcard.delayed_periods_num_3}}</td>
				<td>{{overdue_creditcard.delayed_periods_num_6}}</td>
				<td>{{overdue_creditcard.delayed_periods_num_12}}</td>
			</tr>
			<tr>
				<td>延滞金银行机构数</td>
				<td>{{overdue_creditcard.delayed_bank_num_3}}</td>
				<td>{{overdue_creditcard.delayed_bank_num_6}}</td>
				<td>{{overdue_creditcard.delayed_bank_num_12}}</td>
			</tr>
			<tr>
				<td>延滞金卡片数</td>
				<td>{{overdue_creditcard.delayed_card_num_3}}</td>
				<td>{{overdue_creditcard.delayed_card_num_6}}</td>
				<td>{{overdue_creditcard.delayed_card_num_12}}</td>
			</tr>
			<tr>
				<td>首次延滞金额</td>
				<td>{{overdue_creditcard.delayed_amnt_first_3}}</td>
				<td>{{overdue_creditcard.delayed_amnt_first_6}}</td>
				<td>{{overdue_creditcard.delayed_amnt_first_12}}</td>
			</tr>
			<tr>
				<td>最高（超额金+滞纳金）金额</td>
				<td>{{overdue_creditcard.max_amnt_of_beyond_delayed_3}}</td>
				<td>{{overdue_creditcard.max_amnt_of_beyond_delayed_6}}</td>
				<td>{{overdue_creditcard.max_amnt_of_beyond_delayed_12}}</td>
			</tr>
			<tr>
				<td>最高延滞金额</td>
				<td>{{overdue_creditcard.max_beyond_amnt_3}}</td>
				<td>{{overdue_creditcard.max_beyond_amnt_6}}</td>
				<td>{{overdue_creditcard.max_beyond_amnt_12}}</td>
			</tr>
			<tr>
				<td>最高延滞状态</td>
				<td>{{overdue_creditcard.highest_delayed_3}}</td>
				<td>{{overdue_creditcard.highest_delayed_6}}</td>
				<td>{{overdue_creditcard.highest_delayed_12}}</td>
			</tr>
			<tr>
				<td>最近产生延滞金额距今的月份数</td>
				<td>{{overdue_creditcard.last_delayed_mon_num_3}}</td>
				<td>{{overdue_creditcard.last_delayed_mon_num_6}}</td>
				<td>{{overdue_creditcard.last_delayed_mon_num_12}}</td>
			</tr>
			<tr>
				<td>逾期期数为1的月份数</td>
				<td>{{overdue_creditcard.case_delayed_period_equals_one_mon_num_3}}</td>
				<td>{{overdue_creditcard.case_delayed_period_equals_one_mon_num_6}}</td>
				<td>{{overdue_creditcard.case_delayed_period_equals_one_mon_num_12}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.9固定属性</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>有账单的月份数</td>
				<td>{{other_attribute.have_bill_month_num_nearly_3}}</td>
				<td>{{other_attribute.have_bill_month_num_nearly_6}}</td>
				<td>{{other_attribute.have_bill_month_num_nearly_12}}</td>
			</tr>
			<tr>
				<td>连续账单的最大月份数</td>
				<td>{{other_attribute.longest_month_of_continuous_bill_nearly_3}}</td>
				<td>{{other_attribute.longest_month_of_continuous_bill_nearly_6}}</td>
				<td>{{other_attribute.longest_month_of_continuous_bill_nearly_12}}</td>
			</tr>
			<tr>
				<td>无账单月数</td>
				<td>{{other_attribute.none_bill_month_num_nearly_3}}</td>
				<td>{{other_attribute.none_bill_month_num_nearly_6}}</td>
				<td>{{other_attribute.none_bill_month_num_nearly_12}}</td>
			</tr>
			<tr>
				<td>无账单月数/可统计的月数</td>
				<td>{{other_attribute.none_bill_month_num_per_all_3}}</td>
				<td>{{other_attribute.none_bill_month_num_per_all_6}}</td>
				<td>{{other_attribute.none_bill_month_num_per_all_12}}</td>
			</tr>
			<tr>
				<td>单卡最长连续账单月数</td>
				<td>{{other_attribute.longest_num_of_continuous_bill_nearly_3}}</td>
				<td>{{other_attribute.longest_num_of_continuous_bill_nearly_6}}</td>
				<td>{{other_attribute.longest_num_of_continuous_bill_nearly_12}}</td>
			</tr>
			<tr>
				<td>单卡最大账单断开月数</td>
				<td>{{other_attribute.single_card_disconnect_month_num_3}}</td>
				<td>{{other_attribute.single_card_disconnect_month_num_6}}</td>
				<td>{{other_attribute.single_card_disconnect_month_num_12}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
</form>
