<%@ page contentType="text/html;charset=UTF-8" %>

<form class="layui-form" action="">
   {{#each reportData}}
    <%--信用卡邮箱报告--%>
    <fieldset class="layui-elem-field">
        <legend>1.1用户基本信息</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr>
                <td>姓名：{{user_basic_information.name}}</td>
                <td>邮箱：{{user_basic_information.email}}</td>
            </tr>
              <tr>
                <td>活跃卡数：{{user_basic_information.active_cards}}</td>
                <td>银行数：{{user_basic_information.bank_nums}}</td>
            </tr>
            <tr>
                <td>最初账单日：{{user_basic_information.first_bill_date}}</td>
                <td>最早一期账单距今月份数：{{user_basic_information.first_bill_months_from_now}}</td>
            </tr>
            <tr>
                <td>客户族群标志：{{user_basic_information.customer_group_tag}}</td>
                <td>客户套现标志：{{user_basic_information.cash_out_tag}}</td>
            </tr>
            <tr>
                <td>账单最新认证时间：{{user_basic_information.latest_authentication_time}}</td>
                <td>近6月本人一手账单占所有账单比例：{{user_basic_information.ratio_original_bill_div_all_bills_l6m}}</td>
            </tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>1.2授信情况</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr><td>总信用额</td><td>{{credit_limit_informatin.total_credit_limit}}</td></tr>
			<tr><td>消费信用额</td><td>{{credit_limit_informatin.total_consume_credit_limit}}</td></tr>
			<tr><td>提现信用额</td><td>{{credit_limit_informatin.total_cash_limit}}</td></tr>
			<tr><td>可用提现信用额</td><td>{{credit_limit_informatin.aviable_cash_limit}}</td></tr>
			<tr><td>可用消费信用额</td><td>{{credit_limit_informatin.aviable_consume_credit_limit}}</td></tr>
			<tr><td>总可用信用额</td><td>{{credit_limit_informatin.total_aviable_credit_limit}}</td></tr>
			<tr><td>单一银行最高授信额度</td><td>{{credit_limit_informatin.max_total_credit_limit}}</td></tr>
			<tr><td>单一银行最低授信额度</td><td>{{credit_limit_informatin.min_total_credit_limit}}</td></tr>
            </tbody>
        </table>
    </fieldset>
   	<fieldset class="layui-elem-field">
        <legend>1.3交易行为</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr><td>当期新发生消费总金额</td><td>{{transaction_information.total_current_consume}}</td></tr>
			<tr><td>当期总透支余额</td><td>{{transaction_information.total_current_new_balance}}</td></tr>
			<tr><td>上期应还总额</td><td>{{transaction_information.total_last_new_balance}}</td></tr>
			<tr><td>当期最低还款总额</td><td>{{transaction_information.current_total_min_payment}}</td></tr>
			<tr><td>上期未还总额</td><td>{{transaction_information.last_no_payment_total}}</td></tr>
			<tr><td>当期新发生消费总笔数</td><td>{{transaction_information.current_total_consume_count}}</td></tr>
			<tr><td>当期新发生消费平均金额</td><td>{{transaction_information.current_consume_average_amount}}</td></tr>
			<tr><td>当期新发生提现总金额</td><td>{{transaction_information.current_withdraw_amount}}</td></tr>
			<tr><td>当期新发生提现总笔数</td><td>{{transaction_information.current_withdraw_count}}</td></tr>
			<tr><td>当期新发生提现平均金额</td><td>{{transaction_information.current_withdraw_average_amount}}</td></tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>1.4还款</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr><td>还款金额</td><td>{{payment_information.total_payment_amount}}</td></tr>
			<tr><td>还款笔数</td><td>{{payment_information.total_payments_times}}</td></tr>
			<tr><td>还款率</td><td>{{payment_information.repay_ratio}}</td></tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>1.5逾期信息</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
            <tr><td>逾期账单数量</td><td>{{overdue_information.total_overdue_bill_count}}</td></tr>
			<tr><td>未还金额</td><td>{{overdue_information.total_overdue_amount}}</td></tr>
			<tr><td>未还金额占比</td><td>{{overdue_information.total_overdue_amount_div_new_balance}}</td></tr>
			<tr><td>逾期标志</td><td>{{overdue_information.overdue_flag}}</td></tr>
			<tr><td>逾期状态</td><td>{{overdue_information.overdue_status}}</td></tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>1.6利费信息</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            </thead>
            <tbody>
			<tr><td>总利息</td><td>{{interest_fee_information.total_interest_amount}}</td></tr>
			<tr><td>滞纳金</td><td>{{interest_fee_information.total_overdue_fine_amount}}</td></tr>
			<tr><td>超额金</td><td>{{interest_fee_information.total_excess_amount}}</td></tr>
			<tr><td>其他费用</td><td>{{interest_fee_information.total_extra_amount}}</td></tr>
			<tr><td>收入（利息+滞纳金+超额金+其他费用+分期手续费）</td><td>{{interest_fee_information.total_revenue_amount}}</td></tr>
			<tr><td>分期手续费</td><td>{{interest_fee_information.total_installment_fee_amount}}</td></tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.1销售金额</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>销售金额大于0的月份占比</td>
				<td>{{new_charge_information.ratio_sell_l3m}}</td>
				<td>{{new_charge_information.ratio_sell_l6m}}</td>
				<td>{{new_charge_information.ratio_sell_l12m}}</td>
			</tr>
			<tr>
				<td>月均消费金额</td>
				<td>{{new_charge_information.average_consume_l3m}}</td>
				<td>{{new_charge_information.average_consume_l6m}}</td>
				<td>{{new_charge_information.average_consume_l12m}}</td>
			</tr>
			<tr>
				<td>最高消费金额</td>
				<td>{{new_charge_information.max_consume_l3m}}</td>
				<td>{{new_charge_information.max_consume_l6m}}</td>
				<td>{{new_charge_information.max_consume_l12m}}</td>
			</tr>
			<tr>
				<td>最低消费金额</td>
				<td>{{new_charge_information.min_consume_l3m}}</td>
				<td>{{new_charge_information.min_consume_l6m}}</td>
				<td>{{new_charge_information.min_consume_l12m}}</td>
			</tr>
			<tr>
				<td>提现次数</td>
				<td>{{new_charge_information.times_withdraw_deposit_l3m}}</td>
				<td>{{new_charge_information.total_withdraw_count_l6m}}</td>
				<td>{{new_charge_information.total_withdraw_count_l12m}}</td>
			</tr>
			<tr>
				<td>提现金额</td>
				<td>{{new_charge_information.withdraw_amount_l3m}}</td>
				<td>{{new_charge_information.withdraw_amount_l6m}}</td>
				<td>{{new_charge_information.withdraw_amount_l12m}}</td>
			</tr>
			<tr>
				<td>有提现月数占比</td>
				<td>{{new_charge_information.ratio_withdraw_months_div_all_months_l3m}}</td>
				<td>{{new_charge_information.ratio_withdraw_months_div_all_months_l6m}}</td>
				<td>{{new_charge_information.ratio_withdraw_months_div_all_months_l12m}}</td>
			</tr>
			<tr>
				<td>月均提现金额</td>
				<td>{{new_charge_information.average_withdraw_amount_l3m}}</td>
				<td>{{new_charge_information.average_withdraw_amount_l6m}}</td>
				<td>{{new_charge_information.average_withdraw_amount_l12m}}</td>
			</tr>
			<tr>
				<td>最近一次提现距今的月数</td>
				<td>{{new_charge_information.months_from_last_withdraw_l3m}}</td>
				<td>{{new_charge_information.months_from_last_withdraw_l6m}}</td>
				<td>{{new_charge_information.months_from_last_withdraw_l12m}}</td>
			</tr>
			<tr>
				<td>首次销售金额</td>
				<td>{{new_charge_information.first_sell_amount_l3m}}</td>
				<td>{{new_charge_information.first_sell_amount_l6m}}</td>
				<td>{{new_charge_information.first_sell_amount_l12m}}</td>
			</tr>
			<tr>
				<td>首次消费金额</td>
				<td>{{new_charge_information.first_consume_amount_l3m}}</td>
				<td>{{new_charge_information.first_consume_amount_l6m}}</td>
				<td>{{new_charge_information.first_consume_amount_l12m}}</td>
			</tr>
			<tr>
				<td>单期最大销售笔数</td>
				<td>{{new_charge_information.max_sell_count_l3m}}</td>
				<td>{{new_charge_information.max_sell_count_l6m}}</td>
				<td>{{new_charge_information.max_sell_count_l12m}}</td>
			</tr>
			<tr>
				<td>有销售的月数</td>
				<td>{{new_charge_information.months_have_sell_l3m}}</td>
				<td>{{new_charge_information.months_have_sell_l6m}}</td>
				<td>{{new_charge_information.months_have_sell_l12m}}</td>
			</tr>
			<tr>
				<td>月均消费笔数</td>
				<td>{{new_charge_information.average_sell_count_l3m}}</td>
				<td>{{new_charge_information.average_sell_count_l6m}}</td>
				<td>{{new_charge_information.average_sell_count_l12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.2余额</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>近1月零售余额/近＊月均零售余额</td>
				<td>{{new_balance_information.new_balance_l1m_div_l3m}}</td>
				<td>{{new_balance_information.new_balance_l1m_div_l6m}}</td>
				<td>{{new_balance_information.new_balance_l1m_div_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月均销售占近＊月均余额比率</td>
				<td>{{new_balance_information.l3m_sell_div_l3m_new_balance}}</td>
				<td>{{new_balance_information.l6m_sell_div_l6m_new_balance}}</td>
				<td>{{new_balance_information.l12m_sell_div_l12m_new_balance}}</td>
			</tr>
			<tr>
				<td>近＊月最高余额距今的月数</td>
				<td>{{new_balance_information.months_max_balance_from_now_l3m}}</td>
				<td>{{new_balance_information.months_max_balance_from_now_l6m}}</td>
				<td>{{new_balance_information.monts_max_balance_from_now_l12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.3还款</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>近＊月平均还款金额</td>
				<td>{{payment_analyze_information.average_payment_amount_l3m}}</td>
				<td>{{payment_analyze_information.average_payment_amount_l6m}}</td>
				<td>{{payment_analyze_information.average_payment_amount_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月平均还款率</td>
				<td>{{payment_analyze_information.average_payment_ratio_l3m}}</td>
				<td>{{payment_analyze_information.average_payment_ratio_l6m}}</td>
				<td>{{payment_analyze_information.average_payment_ratio_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月最近一次产生还款金额距今的月数</td>
				<td>{{payment_analyze_information.months_last_payment_from_now_l3m}}</td>
				<td>{{payment_analyze_information.months_last_payment_from_now_l6m}}</td>
				<td>{{payment_analyze_information.months_last_payment_from_now_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月有最低还款且不足全额的月数</td>
				<td>{{payment_analyze_information.months_min_payment_less_new_balance_l3m}}</td>
				<td>{{payment_analyze_information.months_min_payment_less_new_balance_l6m}}</td>
				<td>{{payment_analyze_information.months_min_payment_less_new_balance_l12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.4额度</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>近＊月平均余额占额度比例</td>
				<td>{{credit_limit_analyze_informatin.new_balance_div_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.average_new_balance_div_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.average_new_balance_div_credit_limit_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月可用额度</td>
				<td>{{credit_limit_analyze_informatin.total_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.total_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.total_credit_limit_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月销售金额占额度比</td>
				<td>{{credit_limit_analyze_informatin.new_charge_div_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.sell_div_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.sell_div_credit_limit_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月中最大销售金额占额度比</td>
				<td>{{credit_limit_analyze_informatin.max_sell_div_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.max_sell_div_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.max_sell_div_credit_limit_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月中最小销售金额占额度比</td>
				<td>{{credit_limit_analyze_informatin.min_sell_div_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.min_sell_div_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.min_sell_div_credit_limit_12m}}</td>
			</tr>
			<tr>
				<td>近＊月最大额度使用率</td>
				<td>{{credit_limit_analyze_informatin.max_new_balance_div_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.max_new_balance_div_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.max_new_balance_div_credit_limit_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月最近一次额度使用率>0的值</td>
				<td>{{credit_limit_analyze_informatin.latest_ratio_above_zero_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.latest_ratio_above_zero_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.latest_ratio_above_zero_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月平均（消费+提现）金额/信用额度</td>
				<td>{{credit_limit_analyze_informatin.average_sell_div_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.average_sell_div_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.average_sell_div_credit_limit_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月中销售金额占额度比大于0.5的月数</td>
				<td>{{credit_limit_analyze_informatin.months_sell_div_credit_limit_above_half_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.months_new_sell_div_credit_limit_above_half_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.months_new_sell_div_credit_limit_above_half_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月中销售金额占额度比大于0.9的月数</td>
				<td>{{credit_limit_analyze_informatin.monhts_new_balance_div_credit_limit_above_90pct_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.months_new_sell_div_credit_limit_above_90pct_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.months_new_sell_div_credit_limit_above_90pct_l12m}}</td>
			</tr>
			<tr>
				<td>最近一期额度使用率与近＊月最大比</td>
				<td>{{credit_limit_analyze_informatin.max_ratio_latest_month_usage_ratio_div_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.max_ratio_latest_month_usage_ratio_div_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.max_ratio_latest_month_usage_ratio_div_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月平均额度</td>
				<td>{{credit_limit_analyze_informatin.average_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.average_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.average_credit_limit_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月最高额度</td>
				<td>{{credit_limit_analyze_informatin.max_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.max_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.max_credit_limit_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月最低额度</td>
				<td>{{credit_limit_analyze_informatin.min_credit_limit_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.min_credit_limit_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.min_credit_limit_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月最小额度使用率</td>
				<td>{{credit_limit_analyze_informatin.min_credit_limit_usage_ratio_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.min_credit_limit_usage_ratio_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.min_credit_limit_usage_ratio_l12m}}</td>
			</tr>
			<tr>
				<td>近＊月平均额度使用率</td>
				<td>{{credit_limit_analyze_informatin.average_credit_limit_usage_ratio_l3m}}</td>
				<td>{{credit_limit_analyze_informatin.average_credit_limit_usage_ratio_l6m}}</td>
				<td>{{credit_limit_analyze_informatin.average_credit_limit_usage_ratio_l12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.5利息</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>有利息的月份数</td>
				<td>{{interest_fee_analyze_information.months_with_interest_l3m}}</td>
				<td>{{interest_fee_analyze_information.months_with_interest_l6m}}</td>
				<td>{{interest_fee_analyze_information.months_with_interest_l12m}}</td>
			</tr>
			<tr>
				<td>有利息月数占比</td>
				<td>{{interest_fee_analyze_information.interest_months_ratio_l3m}}</td>
				<td>{{interest_fee_analyze_information.interest_months_ratio_l6m}}</td>
				<td>{{interest_fee_analyze_information.interest_months_ratio_l12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.6收入</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>平均收入</td>
				<td>{{incoming_information.average_income_l3m}}</td>
				<td>{{incoming_information.average_income_l6m}}</td>
				<td>{{incoming_information.average_income_l12m}}</td>
			</tr>
			<tr>
				<td>最低收入距今月份数</td>
				<td>{{incoming_information.months_min_income_from_now_l3m}}</td>
				<td>{{incoming_information.months_min_income_from_now_l6m}}</td>
				<td>{{incoming_information.months_min_income_from_now_l12m}}</td>
			</tr>
			<tr>
				<td>近3个月平均收入与近6个月平均比</td>
				<td colspan="3">{{incoming_information.average_income_l3m_div_average_income_l6m}}</td>
			</tr>
			<tr>
				<td>近6个月平均收入与近12个月平均比</td>
				<td colspan="3">{{incoming_information.ratio_l6m_average_income_div_l12M_average_income}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.7超额</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>超额的月份数</td>
				<td>{{excess_information.excess_months_l3m}}</td>
				<td>{{excess_information.excess_months_l6m}}</td>
				<td>{{excess_information.excess_months_l12m}}</td>
			</tr>
			<tr>
				<td>最高超额费</td>
				<td>{{excess_information.max_excess_fee_l3m}}</td>
				<td>{{excess_information.max_excess_fee_l6m}}</td>
				<td>{{excess_information.max_excess_fee_l12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.8逾期</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>非延滞期数</td>
				<td>{{overdue_analyze_information.months_not_overdue_l3m}}</td>
				<td>{{overdue_analyze_information.months_not_overdue_l6m}}</td>
				<td>{{overdue_analyze_information.months_not_overdue_l12m}}</td>
			</tr>
			<tr>
				<td>延滞期数</td>
				<td>{{overdue_analyze_information.months_ovderdue_l3m}}</td>
				<td>{{overdue_analyze_information.months_ovderdue_l6m}}</td>
				<td>{{overdue_analyze_information.months_ovderdue_l12m}}</td>
			</tr>
			<tr>
				<td>延滞金银行机构数</td>
				<td>{{overdue_analyze_information.banks_withdraw_overdue_fine_l3m}}</td>
				<td>{{overdue_analyze_information.banks_withdraw_overdue_fine_l6m}}</td>
				<td>{{overdue_analyze_information.banks_withdraw_overdue_fine_l12m}}</td>
			</tr>
			<tr>
				<td>延滞金卡片数</td>
				<td>{{overdue_analyze_information.card_nums_with_overdue_fine_l3m}}</td>
				<td>{{overdue_analyze_information.card_nums_with_overdue_fine_l6m}}</td>
				<td>{{overdue_analyze_information.card_nums_with_overdue_fine_l12m}}</td>
			</tr>
			<tr>
				<td>首次延滞金额</td>
				<td>{{overdue_analyze_information.first_overdue_amount_l3m}}</td>
				<td>{{overdue_analyze_information.first_overdue_amount_l6m}}</td>
				<td>{{overdue_analyze_information.first_overdue_amount_l12m}}</td>
			</tr>
			<tr>
				<td>最高（超额金+滞纳金）金额</td>
				<td>{{overdue_analyze_information.max_excess_and_overdue_fine_amount}}</td>
				<td>{{overdue_analyze_information.max_excess_and_overdue_fine_amount_l6m}}</td>
				<td>{{overdue_analyze_information.max_excess_and_overdue_fine_amount_l12m}}</td>
			</tr>
			<tr>
				<td>最高延滞金额</td>
				<td>{{overdue_analyze_information.max_overdue_fine_l3m}}</td>
				<td>{{overdue_analyze_information.max_overdue_fine_l6m}}</td>
				<td>{{overdue_analyze_information.max_overdue_fine_l12m}}</td>
			</tr>
			<tr>
				<td>最高延滞状态</td>
				<td>{{overdue_analyze_information.max_overdue_status_l3m}}</td>
				<td>{{overdue_analyze_information.max_overdue_status_l3m}}</td>
				<td>{{overdue_analyze_information.max_overdue_status_l12m}}</td>
			</tr>
			<tr>
				<td>最近产生延滞金额距今的月份数</td>
				<td>{{overdue_analyze_information.months_last_overdue_months_from_now_l3m}}</td>
				<td>{{overdue_analyze_information.months_last_overdue_months_from_now_l6m}}</td>
				<td>{{overdue_analyze_information.months_last_overdue_months_from_now_l12m}}</td>
			</tr>
			<tr>
				<td>逾期期数为1的月份数</td>
				<td>{{overdue_analyze_information.months_overdue_1_months_l3m}}</td>
				<td>{{overdue_analyze_information.months_overdue_1_months_l6m}}</td>
				<td>{{overdue_analyze_information.months_overdue_1_months_l12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="layui-elem-field">
        <legend>2.9固定属性</legend>
        <table class="layui-table" lay-even="" lay-skin="row">
            <colgroup>
            	<col width="400">
            </colgroup>
            <thead>
            <tr>
                <th>魔蝎变量</th>
                <th>近3月</th>
                <th>近6月</th>
                <th>近12月</th>
            </tr>
            </thead>
            <tbody>
			<tr>
				<td>有账单的月份数</td>
				<td>{{fix_attribute_information.months_have_bill_l3m}}</td>
				<td>{{fix_attribute_information.months_have_bill_l6m}}</td>
				<td>{{fix_attribute_information.months_have_bill_l12m}}</td>
			</tr>
			<tr>
				<td>连续账单的最大月份数</td>
				<td>{{fix_attribute_information.max_months_have_succession_bills_l3m}}</td>
				<td>{{fix_attribute_information.max_months_have_succession_bills_l6m}}</td>
				<td>{{fix_attribute_information.max_months_have_succession_bills_l12m}}</td>
			</tr>
			<tr>
				<td>无账单月数</td>
				<td>{{fix_attribute_information.months_without_bill_l3m}}</td>
				<td>{{fix_attribute_information.months_without_bill_l6m}}</td>
				<td>{{fix_attribute_information.months_without_bill_l12m}}</td>
			</tr>
			<tr>
				<td>无账单月数/可统计的月数</td>
				<td>{{fix_attribute_information.months_without_bills_l3m_div_all_months_have_bill}}</td>
				<td>{{fix_attribute_information.months_without_bills_l6m_div_all_months_have_bill}}</td>
				<td>{{fix_attribute_information.months_without_bills_l12m_div_all_months_have_bill}}</td>
			</tr>
			<tr>
				<td>单卡最长连续账单月数</td>
				<td>{{fix_attribute_information.max_months_single_card_succession_bills_l3m}}</td>
				<td>{{fix_attribute_information.max_months_single_card_succession_bills_l6m}}</td>
				<td>{{fix_attribute_information.max_months_single_card_succession_bill_l12m}}</td>
			</tr>
			<tr>
				<td>单卡最大账单断开月数</td>
				<td>{{fix_attribute_information.max_months_single_card_break_l3m}}</td>
				<td>{{fix_attribute_information.max_months_single_card_break_l6m}}</td>
				<td>{{fix_attribute_information.max_months_single_card_break_l12m}}</td>
			</tr>
            </tbody>
        </table>
    </fieldset>
    {{/each}}
</form>
